- name: Enabling GigabitEthernet0/1
  hosts: routers
  tasks:
    - name: Turn on interfaces
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents:
          - interface GigabitEthernet0/1

- name: Creating Sub-interfaces 
  hosts: routers
  tasks:
    - name: Create Gi0/1.10 
      cisco.ios.ios_config:
        lines:
          - encapsulation dot1Q 10
          - description Management VLAN
          - ip address 10.10.10.2 255.255.255.192
        parents:
          - interface GigabitEthernet0/1.10

    - name: Create Gi0/1.20
      cisco.ios.ios_config:
        lines:
          - encapsulation dot1Q 20
          - description Users VLAN
          - ip address 10.10.10.66 255.255.255.192
        parents:
          - interface GigabitEthernet0/1.20
          
    - name: Create Gi0/1.30
      cisco.ios.ios_config:
        lines:
          - encapsulation dot1Q 30
          - description Reserved VLAN
          - ip address 10.10.10.130 255.255.255.192
        parents:
          - interface GigabitEthernet0/1.30

# Seeing that it's not saving, this is needed.
- name: Save configuration
  hosts: routers
  tasks:
    - name: Save configuration if modified
      cisco.ios.ios_config:
        save_when: modified